# Generated by Django 3.0.1 on 2019-12-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mg',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
